import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Byte Sized</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Byte Sized!</a>
        </h1>

        <p className={styles.description}>
          Thanks for taking the first step in reducing food waste! 
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>User Registration &rarr;</h2>
            <p>Not signed up? Create a new account here to score exclusive deals.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Store Registration &rarr;</h2>
            <p>Not signed up? Create a new account here to start selling.</p>
          </a>

          <a
            href="/login"
            className={styles.card}
          >
            <h2>User Login &rarr;</h2>
            <p>Login into your account to acesss your personalized account.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Store Login &rarr;</h2>
            <p>
            Login into your account to acesss your restaurant profile.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
